version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=
      - DISCORD_MAX_HISTORY=20
      - DISCORD_LANG=en
      - AI_CLIENT=openAI
      - OPENAI_API_KEY=
      - OPENAI_MODEL=gpt-4o
      - OPENAI_IMAGE_SIZE=1024x1024
      - OPENAI_MAX_TOKENS=4000
      - OPENAI_TEMPERATURE=0.5
      - CLAUDE_API_KEY=
      - CLAUDE_MODEL=claude-3-5-sonnet-20240620
      - CLAUDE_MAX_TOKENS=2000
      - CLAUDE_TEMPERATURE=0.5
      - DUNE_ACTIVE=false
      - DUNE_API_KEY=
      - SERP_ACTIVE=false
      - SERP_API_KEY=
      - SERP_GOOGLE_DOMAIN=
      - SERP_GL=us
      - SERP_HL=en
      - BRAVE_SEARCH_API_KEY=
      - BRAVE_SEARCH_LANG=
      - BRAVE_SEARCH_ACTIVE=false
      - COIN_ACTIVE=false
      - COIN_API_KEY=
      - COIN_DEFAULT_ASSET=USD
      - GOOGLE_LIGHTHOUSE_ACTIVE=false
      - GOOGLE_LIGHTHOUSE_API_KEY=
      - FLUX_API_ACTIVE=false
      - FLUX_API_KEY=
      - DALLE_API_KEY=
      - DALLE_IMAGE_SIZE=1024x1024
      - DALLE_ACTIVE=false
      - GOOGLE_SEARCH_ACTIVE=false
      - GOOGLE_SEARCH_API_KEY=
      - GOOGLE_SEARCH_CX=
    volumes:
      - ./src:/usr/src/app/src
      - ./tmp:/usr/src/app/tmp

volumes:
  tmp: