name: New PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, go-ts, remove-any]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract PR Diff
        run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > pr_diff.txt
        
      - name: Make script executable
        run: chmod +x ./scripts/gpt-pr.sh

      - name: Analyze and Comment with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ./scripts/gpt-pr.sh $OPENAI_API_KEY $GITHUB_TOKEN $REPO $PR_NUMBER